### ISSUE TITLE
Add relevant blob columns in database to save file uploads

### ISSUE THREAD

**Issue by iamkotwala** [knrbaroda/MSUAdmission_2020#5]
I was making the "file-upload" function, to save the files(10th-12th mark sheets, Aadhar etc.) into the database. But, I couldn't find the relevant blob columns in the "applicant-info" table.
If we need to make a separate table, then I'll do it that way.

**Comment by iamkotwala** [comment]
I was making the "file-upload" function, to save the files(10th-12th mark sheets, Aadhar etc.) into the database. But, I couldn't find the relevant blob columns in the "applicant-info" table.
If we need to make a separate table, then I'll do it that way.

**Comment by Meghna-desai** [comment]
Can we talk on phone call for the same please?

**Comment by iamkotwala** [comment]
We are not storing any blob files on the database until the present or a specified or implied time.
