### ISSUE TITLE
Different Datatypes

### ISSUE THREAD

**Issue by iamkotwala** [knrbaroda/MSUAdmission_2020#7]
Consider the column "SportsPerson" in the database, under the "applicant_info" table. It has "tinyint" as a datatype.
(find it under MSUAdmission_2020/Database/fos_admissiondb_2020.sql)

Now, in excel, the values are in "yes" and "no" which is a string. (find it under MSUAdmission_2020/Database/applicant.xlsx)

**Also, there are many such columns.**

What datatype we should keep?

**Comment by iamkotwala** [comment]
I'm trying to solve the problem by converting the datatypes in java

**Comment by iamkotwala** [comment]
I'm trying to solve the problem by converting the datatypes in java

**Comment by Meghna-desai** [comment]
when I give boolean in mysql it converts to tinyint in table structure so in cases where there is yes db can store 1 and where no db can store 0, is that ok?

**Comment by iamkotwala** [comment]
Yes, ma'am, I have done that way only
