### ISSUE TITLE
CandidateProfileGUI

### ISSUE THREAD

**Issue by hetaparekh** [knrbaroda/MSUAdmission_2020#8]
Remove hyperlink for Fee payment and Download Fee receipt from the , left pane. according to the revised requirements document, we are not supposed to provide these functionalities
![Capture](https://user-images.githubusercontent.com/65341434/85683255-aed4b700-b6ea-11ea-9195-57184157d529.PNG)

**Comment by ebenezer-isaac** [comment]
okay maam
